service: update-cloudfront-sgs

provider:
  name: aws
  runtime: python2.7
  stage: production
  region: us-west-2

iamRoleStatements:
  -
    Effect: Allow
    Action:
      - 'ec2:AuthorizeSecurityGroupIngress'
      - 'ec2:RevokeSecurityGroupIngress'
    Resource: 'arn:aws:ec2:us-west-2:194984328286:security-group/*'
  -
    Effect: Allow
    Action: 'ec2:DescribeSecurityGroups'
    Resource: '*'
  -
    Action:
      - 'logs:CreateLogGroup'
      - 'logs:CreateLogStream'
      - 'logs:PutLogEvents'
    Effect: Allow
    Resource: 'arn:aws:logs:*:*:*'

functions:
  update_security_groups:
    handler: update_security_groups.lambda_handler
