AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An Amazon SNS trigger that logs the message pushed to the SNS topic.
Resources:
  updatesecuritygroups:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: update_security_groups.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: Auto update CloudFront security groups based on SNS message.
      MemorySize: 128
      Timeout: 5
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeSecurityGroups
                - ec2:AuthorizeSecurityGroupIngress
                - ec2:RevokeSecurityGroupIngress
              Resource: '*'
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: arn:aws:sns:us-east-1:806199016981:AmazonIpSpaceChanged

